name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run 1st exercise tests
      run: cargo test --verbose -p ex1
    - name: Run 2nd exercise tests
      run: cargo test --verbose -p ex2
