name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run 1st exercise tests
      run: cargo test --verbose -p ex01
    - name: Run 2nd exercise tests
      run: cargo test --verbose -p ex02
    - name: Run 3rd exercise tests
      run: cargo test --verbose -p ex03
    - name: Run 4th exercise tests
      run: cargo test --verbose -p ex04
    - name: Run 5th exercise tests
      run: cargo test --verbose -p ex05
    - name: Run 6th exercise tests
      run: cargo test --verbose -p ex06
    - name: Run 7th exercise tests
      run: cargo test --verbose -p ex07
    - name: Run 8th exercise tests
      run: cargo test --verbose -p ex08
    - name: Run 9th exercise tests
      run: cargo test --verbose -p ex09
    - name: Run 10th exercise tests
      run: cargo test --verbose -p ex10
    - name: Run 11th exercise tests
      run: cargo test --verbose -p ex11
    - name: Run 12th exercise tests
      run: cargo test --verbose -p ex12
    - name: Run 13th exercise tests
      run: cargo test --verbose -p ex13
    - name: Run 14th exercise tests
      run: cargo test --verbose -p ex14
    - name: Run 15th exercise tests
      run: cargo test --verbose -p ex15
    - name: Run 16th exercise tests
      run: cargo test --verbose -p ex16
    - name: Run 17th exercise tests
      run: cargo test --verbose -p ex17
    - name: Run 18th exercise tests
      run: cargo test --verbose -p ex18
    - name: Run 19th exercise tests
      run: cargo test --verbose -p ex19

